#!/bin/sh

if [[ "$EUID" = 0 ]]; then
    echo "Script being run as root"
    else
        sudo -k # make sure to ask for password on next sudo
            if sudo true; then
                    echo "Acces Granted"
                        else
                                echo "Access Denied"
                                        exit 1
                                            fi
                                            fi

echo 'Installing...'
install -m 755 circa /usr/bin/circa
